# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Submit to survey

inputs:
  android-repository:
    description: 'ground-android repository under test'
    default: andreia-ferreira/test-ground-android

  upload-artifacts:
    description: 'Whether to upload the final emulator data artifacts'
    default: 'false'

  google-maps-key:
    description: 'A Google Maps API key'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.android-repository }}

    - name: Checkout ground-platform
      uses: actions/checkout@v6
      with:
        repository: andreia-ferreira/test-ground-platform
        token: ${{ inputs.token }}
        path: ground-platform

    - name: Check Firebase emulator connection
      shell: bash
      run: |
        echo "Checking connection to Firebase emulator..."
        if curl -v http://localhost:4000; then
            echo "Successfully connected to Firebase emulator!"
        else
            echo "Failed to connect to Firebase emulator (http://localhost:4000)"
            exit 1
        fi

    - name: Validate MAPS_API_KEY
      env:
        MAPS_API_KEY: ${{ inputs.google-maps-key }}
      shell: bash
      run: |
        if [ -z "${MAPS_API_KEY}" ]; then
          echo "MAPS_API_KEY is missing from GitHub secrets"
          exit 1
        fi
        echo "MAPS_API_KEY is set"

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v5

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        MAPS_API_KEY: ${{ inputs.google-maps-key }}
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        disable-animations: true
        script: |
          echo "MAPS_API_KEY=$MAPS_API_KEY" > secrets.properties
          ./gradlew :e2eTest:connectedLocalDebugAndroidTest --stacktrace

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-reports
        path: '**/build/reports/androidTests'
        retention-days: 7
        if-no-files-found: warn

    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-screenshots
        path: '**/build/outputs/connected_android_test_additional_output'
        retention-days: 7
        if-no-files-found: warn


